name: Easy To Learn Guitar
favicon: null
layout_spectrum: 0.7979574759956449
typography_spectrum: 0.17669190233573318
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7873132263775915
  lightness: 0.20714690838940442
  saturation: 0.915853776736185
  rhythmicContrast: 0.7924238790292293
purpose: []
